### ISSUE TITLE
Define constant to represent the HST area

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/stsynphot_refactor#101]
So user code doesn't have to define it every time it needs to do count rate calculations. One can simply import the appropriate module and grab the constant from there.

Define it as a `Quantity` with the appropriate units.

It makes sense to define the HST area in `stsynphot` since the package was meant to support HST anyway.

**Comment by pllim** [comment]
It is a configuration item now:

https://github.com/spacetelescope/stsynphot_refactor/blob/b1d70bd5d2417231736706c82ecaa581f9f0fa28/stsynphot/config.py#L52-L53

It uses [Astropy's configuration system](https://docs.astropy.org/en/stable/config/).

**Comment by pllim** [comment]
To use it:

```python
stsynphot.conf.area
```

**Comment by pllim** [comment]
But if you want `area` to be a `Quantity`, I think I have to add in new code to support that...

**Comment by pllim** [comment]
@ibusko , just to be clear. Is `stsynphot.conf.area` as a float sufficient for your use case, or do you absolutely need a `Quantity`? For backward compatibility, when `area` is passed in without units, it is assumed to be `cm^2`.

**Comment by ibusko** [comment]
It's OK as is. I think that having a Quantity would avoid potential problems for generic users since then the units become attached to the value by definition. But a scalar works fine from the pyetc viewpoint. No need to change it.
Thanks!

**Comment by pllim** [comment]
@ibusko , okay. I am closing this issue then. If you have strong feelings about supporting config item as `Quantity`, please comment upstream at astropy/astropy#9893 . I thought about it a little but I cannot find an elegant way to have `astropy.config` natively supporting `Quantity` without having to patch up the bundled [configobj](https://github.com/astropy/astropy/tree/master/astropy/extern/configobj), which is not trivial.
