### ISSUE TITLE
Error when importing stsynphot

### ISSUE THREAD

**Issue by brentmsmith** [spacetelescope/stsynphot_refactor#69]
##### System information (version)
- stsynphot => 0.1.1
- Operating System / Platform => OS X 10.12.6
- Python => 3.7.3 [Clang 9.0.0 (clang-900.0.39.2)] on darwin

##### Detailed description
importing stsynphot return a warning and an error immediately:
```bash
WARNING: Failed to load Vega spectrum from /grp/hst/cdbs//calspec/alpha_lyr_stis_008.fits; Functionality involving Vega will be cripped: [Errno 2] No such file or directory: '/grp/hst/cdbs//calspec/alpha_lyr_stis_008.fits' [stsynphot.spectrum]
```

##### Steps to reproduce

```python
import stsynphot as STS
```

**Comment by pllim** [comment]
I think this is the same problem as #70 that you reported. You did not install the data files.
