### ISSUE TITLE
Reference new spectral atlas pages

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/stsynphot_refactor#73]
It will be good to update the documentation to include reference to the new pages that now host the spectral atlases:
https://archive.stsci.edu/hlsp/reference-atlases

**Comment by pllim** [comment]
@stscicrawford , thanks for the info! Can you please clarify on whether this is the new default way of doing things, or this is an alternative *in addition* to the existing way?

**Comment by pllim** [comment]
Two obvious places to document this would be:

* https://stsynphot.readthedocs.io/en/latest/stsynphot/data_atlas.html
* https://stsynphot.readthedocs.io/en/latest/stsynphot/appendixa.html

Please let me know if you have other pages in mind.
